-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║  Migration 006 — REAL client catalogue (184 perfumes)                 ║
-- ║                                                                       ║
-- ║  Source: server/data/realCatalog.json (yassine1112's official Fiverr  ║
-- ║  catalogue sent 2026-05-25 — Classic Homme 25, Classic Femme 45,      ║
-- ║  Collection Privée 114).                                              ║
-- ║                                                                       ║
-- ║  Re-running is safe: ON CONFLICT (slug) DO UPDATE.                    ║
-- ║                                                                       ║
-- ║  After running this, run the same data through the dupe_mappings     ║
-- ║  table via the admin Mappages cachés page → "Importer les mappages". ║
-- ╚══════════════════════════════════════════════════════════════════════╝

alter table public.products alter column currency set default 'EUR';

insert into public.products
  (slug, name, tagline, family, gender,
   notes_tete, notes_coeur, notes_fond, season,
   intensity, sillage, longevity, occasions, vibe,
   price, old_price, currency, in_stock, url)
values
  ('stronger', 'STRONGER', 'Armani — Stronger With You Intensely', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('acqua', 'ACQUA', 'Armani — Acqua Di Gio', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('cody', 'CODY', 'Armani — Code', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('want', 'Want', 'Armani/Azzaro — Wanted', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('krom', 'KROM', 'Azzaro — Chrome', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('i-want', 'I WANT', 'Azzaro — Wanted', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('bleu', 'BLEU', 'Chanel — Bleu de Chanel', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('dhi', 'DHI', 'Dior — Dior Homme Intense', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('so', 'SO', 'Dior — Sauvage', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('so-elixir', 'SO ÉLIXIR', 'Dior — Sauvage Elixir', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('fire-24', 'FIRE 24', 'Dior — Fahrenheit', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('king', 'KING', 'D&G — King', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('viril', 'VIRIL', 'JPG — Le Male', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('ultra-viril', 'ULTRA VIRIL', 'JPG — Ultra Male', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('scandal', 'SCANDAL', 'JPG — Scandal Pour Homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('booster', 'BOOSTER', 'Lacoste — Booster', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('blanc', 'BLANC', 'Lacoste — Lacoste Blanc', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('legendaire', 'LEGENDAIRE', 'Montblanc — Legend', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('noirsx', 'NOIRSX', 'Paco Rabanne — Black XS', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('dollars', 'DOLLARS', 'Paco Rabanne — 1 Million', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('invicts', 'INVICTS', 'Paco Rabanne — Invictus', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('spice', 'SPICE', 'Viktor & Rolf — Spicebomb', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('night-men', 'NIGHT MEN', 'YSL — La Nuit de L''Homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('bodyko', 'BODYKO', 'YSL — Body Kouros', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('men-intense', 'MEN INTENSE', 'YSL — L''Homme Intense', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('girly', 'GIRLY', 'Carolina Herrera — Good Girl', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('amoramo', 'AMORAMO', 'Cacharel — Amor Amor', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('melle', 'MELLE', 'Chanel — Coco Mademoiselle', 'Gourmand', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('coco', 'COCO', 'Chanel — Coco Chanel', 'Gourmand', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('class-5', 'CLASS 5', 'Chanel — Chanel N°5', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('tendre', 'TENDRE', 'Chanel — Chance Eau Tendre', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('loe', 'LOÉ', 'Chloé — Chloé', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('i-love-it', 'I LOVE IT', 'Dior — J''adore', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('hypnotic', 'HYPNOTIC', 'Dior — Hypnotic Poison', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('toxic-girl', 'TOXIC GIRL', 'Dior — Poison Girl', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('miss', 'MISS', 'Dior — Miss Chérie', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('imperatrice', 'IMPERATRICE', 'D&G — L''Impératrice', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('is', 'IS', 'Armani — Sì', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('the-way', 'THE WAY', 'Armani — My Way', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('irresistible', 'IRRESISTIBLE', 'Givenchy — Very Irresistible', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('couture', 'COUTURE', 'Givenchy — Hot Couture', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('illicite', 'ILLICITE', 'Givenchy — L''Interdit', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('flora', 'FLORA', 'Gucci — Flora', 'Floral', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('robe', 'ROBE', 'Guerlain — La Petite Robe Noire', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('audace', 'AUDACE', 'Guerlain — Insolence', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('merveilles', 'MERVEILLES', 'Hermès — Eau des Merveilles', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('nuit-b', 'Nuit B', 'Hugo Boss — Boss Nuit', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('nefertiti', 'NEFERTITI', 'JPG — Scandal Pour Femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('s-absolu', 'S.ABSOLU', 'JPG — Scandal Absolu', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('flower', 'FLOWER', 'Kenzo — Flower', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('diamant-noir', 'DIAMANT NOIR', 'Lancôme — La Nuit Trésor', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('bella-vita', 'BELLA VITA', 'Lancôme — La Vie Est Belle', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('her', 'HER', 'Narciso Rodriguez — For Her', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('poudree', 'POUDRÉE', 'Narciso Rodriguez — Poudrée', 'Oriental Boisé', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('ambree', 'AMBRÉE', 'Narciso Rodriguez — Ambrée', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('nani', 'NANI', 'Nina Ricci — Nina', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('lady', 'LADY', 'Paco Rabanne — Lady Million', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('olympe', 'OLYMPE', 'Paco Rabanne — Olympea', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('faming', 'FAMING', 'Paco Rabanne — Fame', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('noirxs-g', 'NOIRXS G', 'Paco Rabanne — Black XS For Her', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('extravagance', 'EXTRAVAGANCE', 'Prada — Paradoxe', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('neila', 'NEILA', 'Mugler — Alien', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('candy', 'CANDY', 'Viktor & Rolf — Bonbon', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('coconut', 'COCONUT', 'Victoria''s Secret — Coconut Passion', 'Gourmand', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('black-tease', 'BLACK TEASE', 'Victoria''s Secret — Tease Noir', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('blacko', 'BLACKO', 'YSL — Black Opium', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('paname', 'PANAME', 'YSL — Mon Paris', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('liberty', 'LIBERTY', 'YSL — Libre', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('manife', 'MANIFE', 'YSL — Manifesto', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('this-is-her', 'THIS IS HER', 'Zadig & Voltaire — This Is Her!', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('aisha', 'AISHA', 'Al-Jazeera — Magic', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('silk', 'SILK', 'Ajmal — Silk Musc', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('solid', 'SOLID', 'Arabian Oud — Solid', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('mada', 'MADA', 'Arabian Oud — Madawi', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('blue-majic', 'BLUE MAJIC', 'Arabian Oud — Crazy Moody', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('mada-gold', 'MADA GOLD', 'Arabian Oud — Madawi Gold', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('arabian-rose', 'ARABIAN ROSE', 'Armani Privé — Rose d''Arabie', 'Floral', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rouge-mala', 'ROUGE MALA', 'Armani Privé — Rouge Malachite', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('lazuli', 'LAZULI', 'Armani Privé — Bleu Lazuli', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sucre-noir', 'SUCRE NOIR', 'Arte Profumi — Sucre Noir', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('hayati', 'HAYATI', 'Attar Collection — Hayati', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('charnel', 'CHARNEL', 'BDK — Gris Charnel', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('street-n9', 'STREET N9', 'Bond No. 9 — Bleecker Street', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('tygar', 'TYGAR', 'Bvlgari — Tygar', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('chaotiq', 'CHAOTIQ', 'Byredo — Rouge Chaotique', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('mula', 'MULA', 'Byron — Mula Mula', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('gourmand-extreme', 'GOURMAND EXTREME', 'Byron — The Chronic', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sultan', 'SULTAN', 'Byron — The Chronic Blue', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('dragon', 'DRAGON', 'Byron — Black Dragon', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('butterfly', 'BUTTERFLY', 'Byron — Green Butterfly', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('oud-malaki', 'OUD MALAKI', 'Chopard — Oud Malaki', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('event-absolu', 'EVENT ABSOLU', 'Creed — Aventus Absolu', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('virgin', 'VIRGIN', 'Creed — Virgin Island Water', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('event', 'EVENT', 'Creed — Aventus', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('bois', 'BOIS', 'Dior — Bois d''Argent', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('bois-intense', 'BOIS INTENSE', 'Dior — Bois Intense', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('gris', 'GRIS', 'Dior — Gris Montaigne', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ambre', 'AMBRE', 'Dior — Ambre Nuit', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('trafalgar', 'TRAFALGAR', 'Dior — Rouge Trafalgar', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('saku', 'SAKU', 'Dior — Sakura', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('colle', 'COLLE', 'Dior — La Colle Noire', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('velvet-oud', 'VELVET OUD', 'D&G — Velvet Desert Oud', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('nectar-d-or', 'NECTAR D''Or', 'Dubaï — Nectar d''Or', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('silver', 'SILVER', 'Dubaï — Nectar Silver', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('fraise-delices', 'FRAISE DÉLICES', 'Dubaï — Délice Fraise', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('musk-tahara', 'MUSK TAHARA', 'Dubaï — Musk Blanc / Musk Tahara', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('musk-blanc-vanille', 'MUSK BLANC VANILLÉ', 'Dubaï — Musk Blanc Vanillé', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sucre-rose', 'SUCRE ROSE', 'Dubaï — Sucre Rose', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('caramelo', 'CARAMELO', 'Dubaï — Vanille & Pistache', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('panacco', 'PANACCO', 'Fomowa — Panna Cotta', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rouge-240', 'ROUGE 240', 'MFK — Baccarat Rouge 540', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rouge-240-intense', 'ROUGE 240 INTENSE', 'MFK — Baccarat Intense', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('oud-satin', 'OUD SATIN', 'MFK — Oud Satin Mood', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('matin', 'MATIN', 'MFK — Petit Matin', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('acqua-forte', 'ACQUA FORTE', 'MFK — Aqua Media Forte', 'Hespéridé Frais', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('soir-de-paris', 'SOIR DE PARIS', 'MFK — Grand Soir', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ravageur', 'RAVAGEUR', 'Frédéric Malle — Musc Ravageur', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('portrait', 'PORTRAIT', 'Frédéric Malle — Portrait of a Lady', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('latte', 'LATTE', 'Giardini di Toscana — Bianco Latte', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('beluga', 'BELUGA', 'Guerlain — Cuir Béluga', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('oud-cherry', 'OUD CHERRY', 'Guerlain — Cherry Oud', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ahojas', 'AHOJAS', 'Hind Al Oud — Ahojas', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('greatness', 'GREATNESS', 'Initio — Oud for Greatness', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('myrrh-tonka', 'MYRRH&TONKA', 'Jo Malone — Myrrh & Tonka', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('28-vanilla', '28 VANILLA', 'Kayali — Vanilla 28', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('pistachio', 'PISTACHIO', 'Kayali — Yum Pistachio Gelato', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('utopia', 'UTOPIA', 'Kayali — Utopia Vanilla Coco', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('marchmallow', 'MARCHMALLOW', 'Kayali — Yum Boujee Marshmallow', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('moonlight', 'MOONLIGHT', 'Kilian — Moonlight in Heaven', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('love', 'LOVE', 'Kilian — Love, Don''t Be Shy', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rolling', 'ROLLING', 'Kilian — Rolling in Love', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('gone-bad', 'GONE BAD', 'Kilian — Good Girl Gone Bad Extreme', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('khamrah', 'KHAMRAH', 'Kilian/Lattafa — Angels'' Share', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('smoking', 'SMOKING', 'Kilian — Smoking Hot', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('krypto', 'KRYPTO', 'Khalil T. — Kryptonite', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('french-kiss', 'FRENCH KISS', 'Khalil T. — French Kiss', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('33-santal', '33 SANTAL', 'Le Labo — Santal 33', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('encre-noir', 'ENCRE NOIR', 'Lalique — Encre Noire', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('azzezah', 'AZZEZAH', 'Lattafa — Azeezah', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('yaara', 'YAARA', 'Lattafa — Yara', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ameerat', 'AMEERAT', 'Lattafa — Ameerat Al Arab', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('nomade', 'NOMADE', 'Louis Vuitton — Ombre Nomade', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('my-dream', 'MY DREAM', 'Louis Vuitton — Attrape-Rêves', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('garden', 'GARDEN', 'Louis Vuitton — Cactus Garden', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('afternoon', 'AFTERNOON', 'Louis Vuitton — Afternoon Swim', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('imaginaire', 'IMAGINAIRE', 'Louis Vuitton — Imagination', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('la-rose-sable', 'LA ROSE SABLÉ', 'Louis Vuitton — Les Sables Roses', 'Floral', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('immense', 'IMMENSE', 'Louis Vuitton — L''Immensité', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('accro-a-la-vanille', 'ACCRO À LA VANILLE', 'Maison Jousset — Accident À La Vanille', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('kobraa', 'KOBRAA', 'Maison Margiela — Sweet Venin', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('creme-brulee', 'CREME BRÛLÉE', 'Maison Mataha — Escapade Gourmande', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rose-vanille', 'ROSE&VANILLE', 'Mancera — Roses Vanille', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('coco-vanilla', 'COCO VANILLA', 'Mancera — Coco Vanille', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('anymede', 'ANYMEDE', 'Marc-Antoine Barrois — Ganymede Extrait', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('daisy', 'DAISY', 'Marc Jacobs — Daisy', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('jazz-night', 'JAZZ NIGHT', 'Maison Margiela — Replica - Jazz Club', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('tonka-arabic', 'TONKA ARABIC', 'Montale — Arabians Tonka', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ani', 'ANI', 'Nishane — Ani', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sweet-desire', 'SWEET DESIRE', 'Nishane — Hundred Silent Ways', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('first-class', 'FIRST CLASS', 'Nobile 1942 — La Danza delle Libellules', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('maestro', 'MAESTRO', 'Nobile 1942 — Capriccio del Maestro', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('pegaz', 'PEGAZ', 'Parfums de Marly — Pegasus', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('delina', 'DELINA', 'Parfums de Marly — Delina', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('liquide-brun', 'LIQUIDE BRUN', 'Parfums de Marly — Althaïr', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('born-in-roma', 'BORN IN ROMA', 'Prada — Uomo Born In Roma', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sucre-d-orient', 'SUCRE D''ORIENT', 'Rasasi — Ebhar', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rs5', 'RS5', 'Rosendo Mateu — No. 5', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('fresh-oud', 'FRESH OUD', 'Rosendo Mateu — Fresh Oud', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('on-fire', 'ON FIRE', 'Stéphane Humbert Lucas — God of Fire', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('venom', 'VENOM', 'Stéphane Humbert Lucas — Venom Incarnat', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('golden-powder', 'GOLDEN POWDER', 'The House of Oud — Golden Powder', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('casanova', 'CASANOVA', 'Tiziana Terenzi — Kirke', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('cherry', 'CHERRY', 'Tom Ford — Lost Cherry', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('neige', 'NEIGE', 'Tom Ford — Soleil Neige', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('fabulous', 'FABULOUS', 'Tom Ford — Fucking Fabulous', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('blanc-soleil', 'BLANC SOLEIL', 'Tom Ford — Soleil Blanc', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('leather', 'LEATHER', 'Tom Ford — Ombré Leather', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('tobacco', 'TOBACCO', 'Tom Ford — Tobacco Vanille', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('erbaggi', 'ERBAGGI', 'Xerjoff — Erba Pura', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('narcos', 'NARCOS', 'Ex Nihilo — Fleur Narcotique', 'Floral', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('l-addiction', 'L''ADDICTION', 'Ulyka — Nota Sugar', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('aramis', 'ARAMIS', 'V Canto — Stricnina', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('bois-d-iris', 'BOIS D''IRIS', 'Van Cleef & Arpels — Bois d''Iris', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('supreme', 'SUPREME', 'YSL — Supreme Bouquet', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive')
on conflict (slug) do update set
  name        = excluded.name,
  tagline     = excluded.tagline,
  family      = excluded.family,
  gender      = excluded.gender,
  price       = excluded.price,
  currency    = excluded.currency,
  in_stock    = excluded.in_stock,
  url         = excluded.url,
  updated_at  = now();

select
  count(*) as total_products,
  count(*) filter (where gender = 'H')              as homme,
  count(*) filter (where gender = 'F')              as femme,
  count(*) filter (where gender = 'U')              as mixte_privee,
  count(*) filter (where currency = 'EUR')          as eur_rows,
  count(*) filter (where in_stock)                  as in_stock
from public.products;
