-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║  Migration 006 — REAL client catalogue (184 perfumes)                 ║
-- ║                                                                       ║
-- ║  Source: server/data/realCatalog.json (yassine1112's official Fiverr  ║
-- ║  catalogue sent 2026-05-25 — Classic Homme 25, Classic Femme 45,      ║
-- ║  Collection Privée 114).                                              ║
-- ║                                                                       ║
-- ║  Re-running is safe: ON CONFLICT (slug) DO UPDATE.                    ║
-- ║                                                                       ║
-- ║  After running this, run the same data through the dupe_mappings     ║
-- ║  table via the admin Mappages cachés page → "Importer les mappages". ║
-- ╚══════════════════════════════════════════════════════════════════════╝

alter table public.products alter column currency set default 'EUR';

insert into public.products
  (slug, name, tagline, family, gender,
   notes_tete, notes_coeur, notes_fond, season,
   intensity, sillage, longevity, occasions, vibe,
   price, old_price, currency, in_stock, url)
values
  ('stronger', 'STRONGER', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('acqua', 'ACQUA', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('cody', 'CODY', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('want', 'Want', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('krom', 'KROM', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('i-want', 'I WANT', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('bleu', 'BLEU', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('dhi', 'DHI', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('so', 'SO', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('so-elixir', 'SO ÉLIXIR', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('fire-24', 'FIRE 24', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('king', 'KING', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('viril', 'VIRIL', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('ultra-viril', 'ULTRA VIRIL', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('scandal', 'SCANDAL', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('booster', 'BOOSTER', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('blanc', 'BLANC', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('legendaire', 'LEGENDAIRE', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('noirsx', 'NOIRSX', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('dollars', 'DOLLARS', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('invicts', 'INVICTS', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('spice', 'SPICE', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('night-men', 'NIGHT MEN', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('bodyko', 'BODYKO', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('men-intense', 'MEN INTENSE', 'Création boisé aromatique pour homme', 'Boisé Aromatique', 'H', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/hommes'),
  ('girly', 'GIRLY', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('amoramo', 'AMORAMO', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('melle', 'MELLE', 'Création gourmand pour femme', 'Gourmand', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('coco', 'COCO', 'Création gourmand pour femme', 'Gourmand', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('class-5', 'CLASS 5', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('tendre', 'TENDRE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('loe', 'LOÉ', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('i-love-it', 'I LOVE IT', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('hypnotic', 'HYPNOTIC', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('toxic-girl', 'TOXIC GIRL', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('miss', 'MISS', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('imperatrice', 'IMPERATRICE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('is', 'IS', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('the-way', 'THE WAY', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('irresistible', 'IRRESISTIBLE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('couture', 'COUTURE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('illicite', 'ILLICITE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('flora', 'FLORA', 'Création floral pour femme', 'Floral', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('robe', 'ROBE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('audace', 'AUDACE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('merveilles', 'MERVEILLES', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('nuit-b', 'Nuit B', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('nefertiti', 'NEFERTITI', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('s-absolu', 'S.ABSOLU', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('flower', 'FLOWER', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('diamant-noir', 'DIAMANT NOIR', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('bella-vita', 'BELLA VITA', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('her', 'HER', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('poudree', 'POUDRÉE', 'Création oriental boisé pour femme', 'Oriental Boisé', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('ambree', 'AMBRÉE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('nani', 'NANI', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('lady', 'LADY', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('olympe', 'OLYMPE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('faming', 'FAMING', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('noirxs-g', 'NOIRXS G', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('extravagance', 'EXTRAVAGANCE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('neila', 'NEILA', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('candy', 'CANDY', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('coconut', 'COCONUT', 'Création gourmand pour femme', 'Gourmand', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('black-tease', 'BLACK TEASE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('blacko', 'BLACKO', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('paname', 'PANAME', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('liberty', 'LIBERTY', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('manife', 'MANIFE', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('this-is-her', 'THIS IS HER', 'Création floral oriental pour femme', 'Floral Oriental', 'F', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/femmes'),
  ('aisha', 'AISHA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('silk', 'SILK', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('solid', 'SOLID', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('mada', 'MADA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('blue-majic', 'BLUE MAJIC', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('mada-gold', 'MADA GOLD', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('arabian-rose', 'ARABIAN ROSE', 'Création floral de la Collection Privée', 'Floral', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rouge-mala', 'ROUGE MALA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('lazuli', 'LAZULI', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sucre-noir', 'SUCRE NOIR', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('hayati', 'HAYATI', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('charnel', 'CHARNEL', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('street-n9', 'STREET N9', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('tygar', 'TYGAR', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('chaotiq', 'CHAOTIQ', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('mula', 'MULA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('gourmand-extreme', 'GOURMAND EXTREME', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sultan', 'SULTAN', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('dragon', 'DRAGON', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('butterfly', 'BUTTERFLY', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('oud-malaki', 'OUD MALAKI', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('event-absolu', 'EVENT ABSOLU', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('virgin', 'VIRGIN', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('event', 'EVENT', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('bois', 'BOIS', 'Création boisé de la Collection Privée', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('bois-intense', 'BOIS INTENSE', 'Création boisé de la Collection Privée', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('gris', 'GRIS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ambre', 'AMBRE', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('trafalgar', 'TRAFALGAR', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('saku', 'SAKU', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('colle', 'COLLE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('velvet-oud', 'VELVET OUD', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('nectar-d-or', 'NECTAR D''Or', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('silver', 'SILVER', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('fraise-delices', 'FRAISE DÉLICES', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('musk-tahara', 'MUSK TAHARA', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('musk-blanc-vanille', 'MUSK BLANC VANILLÉ', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sucre-rose', 'SUCRE ROSE', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('caramelo', 'CARAMELO', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('panacco', 'PANACCO', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rouge-240', 'ROUGE 240', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rouge-240-intense', 'ROUGE 240 INTENSE', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('oud-satin', 'OUD SATIN', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('matin', 'MATIN', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('acqua-forte', 'ACQUA FORTE', 'Création hespéridé frais de la Collection Privée', 'Hespéridé Frais', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('soir-de-paris', 'SOIR DE PARIS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ravageur', 'RAVAGEUR', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('portrait', 'PORTRAIT', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('latte', 'LATTE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('beluga', 'BELUGA', 'Création boisé de la Collection Privée', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('oud-cherry', 'OUD CHERRY', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ahojas', 'AHOJAS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('greatness', 'GREATNESS', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('myrrh-tonka', 'MYRRH&TONKA', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('28-vanilla', '28 VANILLA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('pistachio', 'PISTACHIO', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('utopia', 'UTOPIA', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('marchmallow', 'MARCHMALLOW', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('moonlight', 'MOONLIGHT', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('love', 'LOVE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rolling', 'ROLLING', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('gone-bad', 'GONE BAD', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('khamrah', 'KHAMRAH', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('smoking', 'SMOKING', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('krypto', 'KRYPTO', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('french-kiss', 'FRENCH KISS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('33-santal', '33 SANTAL', 'Création boisé de la Collection Privée', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('encre-noir', 'ENCRE NOIR', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('azzezah', 'AZZEZAH', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('yaara', 'YAARA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ameerat', 'AMEERAT', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('nomade', 'NOMADE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('my-dream', 'MY DREAM', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('garden', 'GARDEN', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('afternoon', 'AFTERNOON', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('imaginaire', 'IMAGINAIRE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('la-rose-sable', 'LA ROSE SABLÉ', 'Création floral de la Collection Privée', 'Floral', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('immense', 'IMMENSE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('accro-a-la-vanille', 'ACCRO À LA VANILLE', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('kobraa', 'KOBRAA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('creme-brulee', 'CREME BRÛLÉE', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rose-vanille', 'ROSE&VANILLE', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('coco-vanilla', 'COCO VANILLA', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('anymede', 'ANYMEDE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('daisy', 'DAISY', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('jazz-night', 'JAZZ NIGHT', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('tonka-arabic', 'TONKA ARABIC', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('ani', 'ANI', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sweet-desire', 'SWEET DESIRE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('first-class', 'FIRST CLASS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('maestro', 'MAESTRO', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('pegaz', 'PEGAZ', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('delina', 'DELINA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('liquide-brun', 'LIQUIDE BRUN', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('born-in-roma', 'BORN IN ROMA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('sucre-d-orient', 'SUCRE D''ORIENT', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('rs5', 'RS5', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('fresh-oud', 'FRESH OUD', 'Création oriental boisé de la Collection Privée', 'Oriental Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('on-fire', 'ON FIRE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('venom', 'VENOM', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('golden-powder', 'GOLDEN POWDER', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('casanova', 'CASANOVA', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('cherry', 'CHERRY', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('neige', 'NEIGE', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('fabulous', 'FABULOUS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('blanc-soleil', 'BLANC SOLEIL', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('leather', 'LEATHER', 'Création boisé de la Collection Privée', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('tobacco', 'TOBACCO', 'Création gourmand de la Collection Privée', 'Gourmand', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('erbaggi', 'ERBAGGI', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('narcos', 'NARCOS', 'Création floral de la Collection Privée', 'Floral', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('l-addiction', 'L''ADDICTION', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('aramis', 'ARAMIS', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('bois-d-iris', 'BOIS D''IRIS', 'Création boisé de la Collection Privée', 'Boisé', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive'),
  ('supreme', 'SUPREME', 'Création oriental mixte de la Collection Privée', 'Oriental Mixte', 'U', '{}', '{}', '{}', '{}', 4, 4, 4, '{}', '', 19.90, null, 'EUR', true, 'https://eleganza-parfums.com/collections/collection-prive')
on conflict (slug) do update set
  name        = excluded.name,
  tagline     = excluded.tagline,
  family      = excluded.family,
  gender      = excluded.gender,
  price       = excluded.price,
  currency    = excluded.currency,
  in_stock    = excluded.in_stock,
  url         = excluded.url,
  updated_at  = now();

select
  count(*) as total_products,
  count(*) filter (where gender = 'H')              as homme,
  count(*) filter (where gender = 'F')              as femme,
  count(*) filter (where gender = 'U')              as mixte_privee,
  count(*) filter (where currency = 'EUR')          as eur_rows,
  count(*) filter (where in_stock)                  as in_stock
from public.products;
